#!/usr/bin/env bash
# https://github.com/jasonk/inform-slack

source inform-slack

tests=0
errors=0
warnings=0
title="*Checkstyle Test Summary*"

parse-file() {
  local file="$1"
  if [ -z "$file" ]; then return; fi
  local files="$(grep -cE '<file' "$file")"
  local errs="$(grep -cE '<error[^>]+severity="error"' "$file")"
  local warns="$(grep -cE '<error[^>]+severity="warning"' "$file")"
  (( tests += files ))
  (( errors += errs ))
  (( warnings += warns ))
}

while (( $# )); do
  case "$1" in
    -T|--title) title="$2"        ; shift 2 ;;
    --title=*)  title="${1#*=}"   ; shift 1 ;;
    -*)         usage "Unknown option '$1'" ;;
    *)          parse-file "$1"   ; shift 1 ;;
  esac
done

run-builder tests-summary --title "$title" \
  --tests $tests --error $errors --warn $warnings --tests-label "Files: "
