#!/usr/bin/env bash
# https://github.com/jasonk/inform-slack

source inform-slack

shell=""

while (( $# )); do
  case "$1" in
    --shell)    shell="$2"                ; shift 2 ;;
    --shell=*)  shell="${1#*=}"           ; shift 1 ;;
    -*)         usage "Unknown option '$1'" ;;
    *)          break                       ;;
  esac
done

if [ -n "${shell:-}" ]; then
  command=( "$shell" "-c" "$@" )
else
  command=( "$@" )
fi

printf -v output '```\n%s\n```\n' "$("${command[@]}")"

block-mrkdwn "$output"
