#!/usr/bin/env bash
# https://github.com/jasonk/inform-slack

source inform-slack

title="*Test Coverage*"

covers=()

parse-file() {
  local FILE="$1"
  # covers+=( "$(jq -c '. |= {command,percent_covered}' "$FILE")" )
  covers+=( "$(jq -r '"\(.command): \(.percent_covered)%"' "$FILE")" )
}

parse-dir() {
  local F
  for F in "$1"/*/coverage.json; do parse-file "$F"; done
}

while (( $# )); do
  case "$1" in
    -T|--title) title="$2"        ; shift 2 ;;
    --title=*)  title="${1#*=}"   ; shift 1 ;;
    -*)         usage "Unknown option '$1'" ;;
    *)          parse-dir "$1"    ; shift 1 ;;
  esac
done

block-section "$title" "$(section-fields "${covers[@]}")"
