#!/usr/bin/env bash
# https://github.com/jasonk/inform-slack

source inform-slack

if (( $# )); then
  for I in "$@"; do block-mrkdwn "$I"; done
fi
if [ -n "${INFORM_SLACK_MESSAGE:-}" ]; then
  block-mrkdwn "$INFORM_SLACK_MESSAGE";
fi
