#!/usr/bin/env bash
# https://github.com/jasonk/inform-slack

source inform-slack

tests=0
pass=0
fail=0
title="*TAP Test Summary*"

parse-file() {
  local file="$1"
  local o="$(grep -cE '^ok\b' "$file" || true)"
  local n="$(grep -cE '^not ok\b' "$file" || true)"
  local p="$(grep -m1 -E '^1..\d+$' "$file" || true)"
  if [ -n "$p" ]; then
    p="${p##*.}"
    (( tests += p ))
  else
    (( tests += o + n ))
  fi
  (( pass += o ))
  (( fail += n ))
}

while (( $# )); do
  case "$1" in
    -T|--title) title="$2"        ; shift 2 ;;
    --title=*)  title="${1#*=}"   ; shift 1 ;;
    -*)         usage "Unknown option '$1'" ;;
    *)          parse-file "$1"   ; shift 1 ;;
  esac
done

run-builder tests-summary --title="$title" \
  --tests=$tests --pass=$pass --fail=$fail
