#!/usr/bin/env bash
# https://github.com/jasonk/inform-slack

source inform-slack

txt=""
title="${INFORM_SLACK_TITLE:-}"
status="${INFORM_SLACK_STATUS:-}"
max="${INFORM_SLACK_PROGRESS_MAX:-}"
pos="${INFORM_SLACK_PROGRESS_POS:-}"
clock="${INFORM_SLACK_PROGRESS_CLOCK:-}"

while (( $# )); do
  case "$1" in
    --text)       txt="$2"          ; shift 2 ;;
    --text=*)     txt="${1#*=}"     ; shift 1 ;;
    -T|--title)   title="$2"        ; shift 2 ;;
    --title=*)    title="${1#*=}"   ; shift 1 ;;
    -S|--status)  status="$2"       ; shift 2 ;;
    --status=*)   status="${1#*=}"  ; shift 1 ;;
    -M|--max)     max="$2"          ; shift 2 ;;
    --max=*)      max="${1#*=}"     ; shift 1 ;;
    -P|--pos)     pos="$2"          ; shift 2 ;;
    --pos=*)      pos="${1#*=}"     ; shift 1 ;;
    --clock)      clock="true"      ; shift 1 ;;
    *)            usage "Unknown option '$1'" ;;
  esac
done

text "${txt:-$title${status:+ - $status}}"

if [ -n "$clock" ]; then
  block-header "$(draw-progress-clock) $title"
else
  block-header "$title"
  block-progress "$pos" "$max"
fi

block-mrkdwn "$status"
